# -*- coding: utf-8 -*-
# Unique, role-specific content for each example page. India-oriented (Naukri, INR, campus).
ROLES = [
{
 'slug':'data-analyst','title':'Data Analyst','badge':'DATA ANALYST','plural':'data analysts',
 'meta':'Free data analyst resume example with a real sample. Build an ATS-friendly data analyst resume with AI in minutes — SQL, Python, Power BI. No sign-up.',
 'og':'See a real data analyst resume example and build yours with AI — ATS-optimised, free, no sign-up.',
 'h1a':'A Data Analyst Resume','h1b':'That Gets Shortlisted',
 'hero':'See a real data analyst resume example, then build yours with AI in minutes. ATS-optimised for Naukri and LinkedIn. No sign-up required.',
 'intro1':'A strong data analyst resume proves two things fast: that you can turn messy data into decisions, and that you know the tools recruiters screen for — SQL, Excel, Python and a BI tool like Power BI or Tableau. Hiring managers skim for quantified impact, not job descriptions.',
 'intro2':'The example below shows how to frame your work as measurable outcomes (revenue saved, hours automated, accuracy improved). Copy the structure, then let our AI rewrite your own bullets into the same punchy, ATS-friendly format.',
 'person':{
   'name':'Priya Sharma','title':'Data Analyst',
   'contact':'priya.sharma@email.com · +91 98xxxxxx21 · Bengaluru, India · linkedin.com/in/priyasharma',
   'summary':'Data Analyst with 4+ years turning raw data into business decisions across e-commerce and fintech. Strong in SQL, Python and Power BI, with a track record of automating reporting and cutting decision time. Reduced monthly reporting effort by 70% and surfaced insights that lifted retention by 12%.',
   'jobs':[
     {'title':'Data Analyst','co':'Flipkart','date':'2022 – Present','bullets':[
       'Built 20+ automated Power BI dashboards that cut manual reporting from 3 days to 4 hours per month',
       'Wrote optimised SQL across 50M+ row tables, reducing query runtime by 65%',
       'Ran cohort and funnel analysis that identified a churn driver, informing a fix that improved 90-day retention by 12%']},
     {'title':'Junior Data Analyst','co':'Paytm','date':'2020 – 2022','bullets':[
       'Automated weekly KPI reports in Python, saving the team ~15 hours/week',
       'Partnered with marketing to A/B test campaigns, improving click-through by 18%']},
   ],
   'skills':['SQL','Python','Excel','Power BI','Tableau','Pandas','Data Cleaning','A/B Testing','Statistics','ETL'],
   'edu':'B.Tech, Information Technology','eduyear':'2020','eduschool':'VIT Vellore · CGPA 8.4','ats':95},
 'include':[
   ('Professional summary','3–4 lines with your years of experience, top tools, and one quantified win.'),
   ('Technical skills','List SQL, Excel and a language (Python/R) plus a BI tool — these are the exact keywords ATS screens for.'),
   ('Quantified experience','Every bullet should have a number: rows processed, time saved, % improvement, revenue impact.'),
   ('Projects (for freshers)','If you have little work experience, add 2–3 analysis projects with the dataset, tools and finding.'),
   ('Education & certifications','Degree, plus any Google Data Analytics, Microsoft Power BI or SQL certifications.'),
 ],
 'skills_intro':'Recruiters and ATS scan for these first. Include the ones you genuinely know:',
 'topskills':['SQL','Excel','Python','Power BI','Tableau','Statistics','Data Visualisation','ETL','A/B Testing','Google Analytics'],
 'faq':[
   ('What should a data analyst resume include?','A short professional summary, a technical skills section (SQL, Excel, Python, a BI tool), 2–4 quantified experience bullets per role, projects if you are a fresher, and education with any relevant certifications.'),
   ('How do I write a data analyst resume with no experience?','Lead with projects instead of jobs: pick 2–3 real datasets, state the tools you used and the insight you found, and quantify it. Add internships, a strong skills section and relevant certifications. Our AI can turn each project into ATS-friendly bullets.'),
   ('Which skills are most important on a data analyst resume?','SQL and Excel are essential, plus at least one of Python or R and one BI tool (Power BI or Tableau). Add statistics, data cleaning and A/B testing if you have them.'),
   ('Is this data analyst resume example free to use?','Yes. Building, editing and previewing your resume is completely free with no sign-up. A PDF download is optional at ₹9 in India (Word download is free).'),
 ],
},
{
 'slug':'business-analyst','title':'Business Analyst','badge':'BUSINESS ANALYST','plural':'business analysts',
 'meta':'Free business analyst resume example with a real sample. Build an ATS-friendly BA resume with AI — requirements, stakeholder, SQL, Agile. No sign-up.',
 'og':'A real business analyst resume example, plus an AI builder to create yours — ATS-optimised and free.',
 'h1a':'A Business Analyst Resume','h1b':'Recruiters Notice',
 'hero':'See a real business analyst resume example, then build yours with AI in minutes. ATS-optimised for Naukri and LinkedIn. No sign-up.',
 'intro1':'A business analyst resume has to show you bridge business and technology: gathering requirements, mapping processes, and delivering change that moves a metric. Recruiters look for outcomes — cost reduced, process time cut, adoption improved — not a list of ceremonies you attended.',
 'intro2':'Use the sample below to frame requirements work and stakeholder management as measurable results, then let AI rewrite your bullets into the same crisp format that passes ATS.',
 'person':{
   'name':'Rahul Mehta','title':'Business Analyst',
   'contact':'rahul.mehta@email.com · +91 99xxxxxx07 · Pune, India · linkedin.com/in/rahulmehta',
   'summary':'Business Analyst with 5 years bridging business and engineering in banking and SaaS. Skilled in requirements gathering, process mapping, SQL and Agile delivery. Led a workflow redesign that cut loan-processing time by 30% and saved ₹1.2Cr annually.',
   'jobs':[
     {'title':'Business Analyst','co':'HDFC Bank','date':'2021 – Present','bullets':[
       'Gathered and documented requirements for a loan-origination revamp, cutting processing time by 30%',
       'Mapped and re-engineered 12 core processes, eliminating rework that saved ₹1.2Cr per year',
       'Wrote SQL to validate data migrations across 3M+ records with zero post-launch defects']},
     {'title':'Associate Business Analyst','co':'Zoho','date':'2019 – 2021','bullets':[
       'Translated business needs into 200+ user stories with clear acceptance criteria for a 9-person Agile team',
       'Built stakeholder dashboards that reduced status-meeting time by 40%']},
   ],
   'skills':['Requirements Gathering','SQL','Agile/Scrum','Process Mapping','JIRA','Stakeholder Management','BRD/FRD','UAT','Wireframing','Data Analysis'],
   'edu':'MBA, Business Analytics','eduyear':'2019','eduschool':'Symbiosis, Pune','ats':94},
 'include':[
   ('Professional summary','State your years, domains (banking, SaaS, retail) and one quantified business outcome.'),
   ('Core BA skills','Requirements gathering, process mapping, SQL, Agile/Scrum, JIRA, UAT — the ATS keywords for BA roles.'),
   ('Outcome-focused experience','Frame each bullet around impact: time saved, cost reduced, adoption or accuracy improved.'),
   ('Tools & documentation','BRD/FRD, user stories, wireframes, dashboards — show the artefacts you actually produce.'),
   ('Education & certifications','Degree plus CBAP, PMI-PBA, or a Scrum certification if you have one.'),
 ],
 'skills_intro':'These BA keywords are what recruiters and ATS filter on:',
 'topskills':['Requirements Gathering','SQL','Agile','Process Mapping','JIRA','Stakeholder Management','UAT','Data Analysis','BRD','Wireframing'],
 'faq':[
   ('What does a good business analyst resume look like?','A concise summary, a skills section with BA keywords (requirements, SQL, Agile, JIRA, UAT), and experience bullets framed as outcomes — time saved, cost reduced, adoption improved — plus your education and any BA certifications.'),
   ('How do I make a business analyst resume with no experience?','Highlight transferable work: analysis coursework, a capstone or internship where you gathered requirements or mapped a process, and tools like Excel, SQL and JIRA. Quantify wherever you can and add a Scrum or CBAP-track certification.'),
   ('Which certifications help a business analyst resume?','CBAP or ECBA (IIBA), PMI-PBA, and a Scrum certification (CSM/PSM) are the most recognised. List them in a dedicated certifications line.'),
   ('Is the business analyst resume builder free?','Yes — build, edit and preview for free with no sign-up. PDF download is ₹9 in India; Word download is free.'),
 ],
},
{
 'slug':'accountant','title':'Accountant','badge':'ACCOUNTANT','plural':'accountants',
 'meta':'Free accountant resume example with a real sample. Build an ATS-friendly accountant resume with AI — Tally, GST, reconciliation, Excel. No sign-up.',
 'og':'A real accountant resume example plus an AI builder to create yours — ATS-optimised and free.',
 'h1a':'An Accountant Resume','h1b':'That Adds Up',
 'hero':'See a real accountant resume example, then build yours with AI in minutes. ATS-optimised for Naukri and finance recruiters. No sign-up.',
 'intro1':'An accountant resume is judged on accuracy, compliance and the tools you use daily — Tally, GST filing, reconciliation and Excel. Recruiters want proof you close books on time and keep the numbers clean, so lead with quantified responsibility (transactions handled, accounts reconciled, audits cleared).',
 'intro2':'The example below shows how to present statutory work and month-end close as measurable outcomes. Let AI rewrite your own duties into the same ATS-friendly, results-first bullets.',
 'person':{
   'name':'Anjali Nair','title':'Senior Accountant',
   'contact':'anjali.nair@email.com · +91 97xxxxxx55 · Kochi, India · linkedin.com/in/anjalinair',
   'summary':'Detail-driven Senior Accountant with 6 years in accounts payable/receivable, GST compliance and month-end close. Expert in Tally ERP and advanced Excel. Reconciled ₹40Cr+ in annual transactions with 99.9% accuracy and cut month-end close from 10 to 6 days.',
   'jobs':[
     {'title':'Senior Accountant','co':'Reliance Retail','date':'2021 – Present','bullets':[
       'Reconciled ₹40Cr+ in annual transactions with 99.9% accuracy across 12 vendor accounts',
       'Cut month-end close from 10 days to 6 by standardising journal entries and automating Excel schedules',
       'Filed monthly GST returns and cleared 3 statutory audits with zero major findings']},
     {'title':'Accountant','co':'Infosys BPM','date':'2018 – 2021','bullets':[
       'Managed accounts payable for 300+ vendors, reducing late payments by 45%',
       'Prepared TDS and GST workings, ensuring 100% on-time statutory compliance']},
   ],
   'skills':['Tally ERP','GST','TDS','Accounts Payable','Accounts Receivable','Bank Reconciliation','Advanced Excel','Month-End Close','Statutory Audit','SAP FICO'],
   'edu':'B.Com (Hons)','eduyear':'2018','eduschool':'Christ University, Bengaluru','ats':93},
 'include':[
   ('Professional summary','Years of experience, core areas (AP/AR, GST, close) and one accuracy/impact number.'),
   ('Accounting software & compliance','Tally, SAP, GST, TDS, reconciliation — the exact keywords finance ATS screens for.'),
   ('Quantified experience','Transactions handled, accounts reconciled, close-time cut, audits cleared — always with numbers.'),
   ('Certifications','CA (Inter/Final), CMA, or a Tally/GST certification — list clearly.'),
   ('Education','B.Com / M.Com with university and year.'),
 ],
 'skills_intro':'These are the accounting keywords recruiters and ATS look for:',
 'topskills':['Tally ERP','GST','TDS','Bank Reconciliation','Advanced Excel','Accounts Payable','Accounts Receivable','SAP FICO','Month-End Close','Statutory Audit'],
 'faq':[
   ('What should an accountant resume include in India?','A summary with your years and specialisms, a skills section with Tally, GST, TDS and Excel, quantified experience (transactions, reconciliations, close time, audits), plus your B.Com/M.Com and any CA/CMA or Tally certification.'),
   ('How do I write an accountant resume for a fresher?','Lead with your B.Com/M.Com, internships, and hands-on tools (Tally, Excel, GST basics). Add academic projects or articleship work and quantify anything you can, like number of invoices processed.'),
   ('Should I mention GST and TDS on my resume?','Yes — GST and TDS are high-value keywords for Indian accounting roles. If you have filed returns or prepared workings, state it explicitly with frequency and volume.'),
   ('Is the accountant resume builder free?','Yes, building and editing are free with no sign-up. PDF download is ₹9 in India; Word is free.'),
 ],
},
{
 'slug':'digital-marketing','title':'Digital Marketing','badge':'DIGITAL MARKETING','plural':'digital marketers',
 'meta':'Free digital marketing resume example with a real sample. Build an ATS-friendly digital marketing resume with AI — SEO, Google Ads, analytics. No sign-up.',
 'og':'A real digital marketing resume example plus an AI builder — ATS-optimised, free, no sign-up.',
 'h1a':'A Digital Marketing Resume','h1b':'That Converts',
 'hero':'See a real digital marketing resume example, then build yours with AI in minutes. ATS-optimised for Naukri and LinkedIn. No sign-up.',
 'intro1':'A digital marketing resume lives and dies on numbers: traffic grown, CAC reduced, ROAS improved, leads generated. Recruiters scan for channels you own (SEO, Google Ads, Meta, email) and the metrics you moved — not vague phrases like "handled social media".',
 'intro2':'Use the example below to turn campaigns into quantified wins, then let AI rewrite your bullets into the same ATS-friendly, metric-first style.',
 'person':{
   'name':'Karan Malhotra','title':'Digital Marketing Manager',
   'contact':'karan.malhotra@email.com · +91 98xxxxxx88 · Gurugram, India · linkedin.com/in/karanmalhotra',
   'summary':'Performance-focused Digital Marketing Manager with 5 years across SEO, paid ads and lifecycle marketing for D2C and SaaS brands. Grew organic traffic 3x and cut customer acquisition cost by 35%. Managed ₹2Cr+ annual ad budgets with a 4.2x ROAS.',
   'jobs':[
     {'title':'Digital Marketing Manager','co':'boAt Lifestyle','date':'2022 – Present','bullets':[
       'Grew organic traffic 3x in 14 months through a technical-SEO and content programme',
       'Managed ₹2Cr+ in Google and Meta ad spend at a 4.2x ROAS, cutting CAC by 35%',
       'Built an email/WhatsApp lifecycle flow that lifted repeat purchases by 22%']},
     {'title':'Performance Marketing Executive','co':'Lenskart','date':'2020 – 2022','bullets':[
       'Ran Google Ads campaigns generating 18,000+ qualified leads at a 28% lower cost per lead',
       'A/B tested landing pages, improving conversion rate from 2.1% to 3.4%']},
   ],
   'skills':['SEO','Google Ads','Meta Ads','Google Analytics 4','Email Marketing','Content Marketing','Conversion Optimisation','SEMrush','Marketing Automation','Copywriting'],
   'edu':'BBA, Marketing','eduyear':'2020','eduschool':'NMIMS, Mumbai','ats':94},
 'include':[
   ('Professional summary','Your years, channels owned (SEO/paid/email) and one headline metric (traffic, ROAS, CAC).'),
   ('Channel & tools skills','SEO, Google Ads, Meta Ads, GA4, SEMrush — the keywords ATS and recruiters screen for.'),
   ('Metric-driven experience','Every bullet needs a number: traffic %, ROAS, CAC, leads, conversion rate.'),
   ('Certifications','Google Ads, GA4, HubSpot or Meta Blueprint — list them; recruiters value them.'),
   ('Portfolio / links','Link a portfolio, a ranked article, or a case study if you have one.'),
 ],
 'skills_intro':'These are the digital marketing keywords ATS and recruiters filter on:',
 'topskills':['SEO','Google Ads','Meta Ads','Google Analytics 4','Email Marketing','Content Marketing','CRO','SEMrush','Marketing Automation','Copywriting'],
 'faq':[
   ('What makes a strong digital marketing resume?','Metrics. State the channels you own and quantify results — organic traffic growth, ROAS, CAC reduction, leads and conversion rate — plus tools (Google Ads, GA4, SEO) and relevant certifications.'),
   ('How do I write a digital marketing resume as a fresher?','Show projects and internships: a blog you grew, a small ad campaign, or a college fest you promoted, with real numbers. Add Google Ads and GA4 certifications (both free) and a skills section with the core channels.'),
   ('Which certifications should I add?','Google Ads, Google Analytics (GA4), HubSpot Content/Inbound, and Meta Blueprint are the most recognised and several are free.'),
   ('Is this resume builder free for marketers?','Yes — build and edit free with no sign-up. PDF download is ₹9 in India; Word is free.'),
 ],
},
{
 'slug':'sales-executive','title':'Sales Executive','badge':'SALES EXECUTIVE','plural':'sales professionals',
 'meta':'Free sales executive resume example with a real sample. Build an ATS-friendly sales resume with AI — targets, revenue, CRM. No sign-up required.',
 'og':'A real sales executive resume example plus an AI builder — ATS-optimised, free, no sign-up.',
 'h1a':'A Sales Executive Resume','h1b':'That Closes Interviews',
 'hero':'See a real sales executive resume example, then build yours with AI in minutes. ATS-optimised for Naukri and LinkedIn. No sign-up.',
 'intro1':'A sales resume is a scoreboard. Recruiters want targets and attainment — quota %, revenue closed, pipeline built, accounts won. Vague duties lose to numbers every time, so lead with quota achievement and deal size.',
 'intro2':'The example below shows how to present targets, revenue and CRM discipline as hard results. Let AI rewrite your own numbers into the same ATS-friendly, achievement-first format.',
 'person':{
   'name':'Vikram Reddy','title':'Sales Executive',
   'contact':'vikram.reddy@email.com · +91 96xxxxxx34 · Hyderabad, India · linkedin.com/in/vikramreddy',
   'summary':'Target-driven Sales Executive with 5 years in B2B SaaS and FMCG. Consistently exceeded quota (avg 128% attainment) and closed ₹6Cr+ in annual revenue. Built and managed a 200+ account pipeline in Salesforce with a 32% win rate.',
   'jobs':[
     {'title':'Sales Executive','co':'Freshworks','date':'2021 – Present','bullets':[
       'Achieved 128% of annual quota, closing ₹6Cr+ in new-business revenue across 40+ accounts',
       'Built a 200+ account pipeline in Salesforce and improved win rate from 24% to 32%',
       'Shortened average sales cycle by 18% through a structured discovery and demo process']},
     {'title':'Business Development Associate','co':'Byju’s','date':'2019 – 2021','bullets':[
       'Generated 500+ qualified leads/quarter via outbound calling and email',
       'Converted at 21% (vs 15% team average), earning top-performer recognition twice']},
   ],
   'skills':['B2B Sales','Salesforce CRM','Lead Generation','Negotiation','Account Management','Cold Calling','Pipeline Management','Upselling','Demo/Presentation','Target Achievement'],
   'edu':'BBA','eduyear':'2019','eduschool':'Christ University, Bengaluru','ats':93},
 'include':[
   ('Professional summary','Years, sales type (B2B/B2C/FMCG), average quota attainment and total revenue closed.'),
   ('Quantified achievements','Quota %, revenue, deal size, win rate, pipeline value, leads — numbers in every bullet.'),
   ('Skills & CRM','B2B/B2C sales, Salesforce/Zoho CRM, negotiation, lead generation — the ATS keywords for sales.'),
   ('Awards & recognition','President’s Club, top performer, rank — recruiters love proof of consistent overachievement.'),
   ('Education','Degree with university and year.'),
 ],
 'skills_intro':'These sales keywords are what recruiters and ATS scan for:',
 'topskills':['B2B Sales','Salesforce CRM','Lead Generation','Negotiation','Account Management','Cold Calling','Pipeline Management','Upselling','Target Achievement','Client Relationship'],
 'faq':[
   ('What should a sales executive resume highlight?','Numbers: quota attainment %, revenue closed, deal size, win rate and pipeline built. Add a skills section (B2B sales, CRM, negotiation, lead gen) and any top-performer awards.'),
   ('How do I write a sales resume with no experience?','Lead with transferable wins — internships, campus placements you drove, fundraising, or part-time sales — with real numbers. Add a skills section with CRM basics and communication, and quantify results wherever possible.'),
   ('Which numbers matter most on a sales resume?','Quota attainment percentage, total revenue closed, average deal size, win/conversion rate and pipeline value. Even one strong number in your summary makes recruiters read on.'),
   ('Is the sales resume builder free?','Yes — build and edit free, no sign-up. PDF download is ₹9 in India; Word is free.'),
 ],
},
{
 'slug':'human-resources','title':'HR Manager','badge':'HUMAN RESOURCES','plural':'HR professionals',
 'meta':'Free HR resume example with a real sample. Build an ATS-friendly human resources resume with AI — recruitment, HRMS, payroll, engagement. No sign-up.',
 'og':'A real HR / human resources resume example plus an AI builder — ATS-optimised and free.',
 'h1a':'An HR Resume','h1b':'That Gets Hired',
 'hero':'See a real HR resume example, then build yours with AI in minutes. ATS-optimised for Naukri and LinkedIn. No sign-up.',
 'intro1':'An HR resume should show you manage people and process at scale: hires closed, time-to-fill reduced, attrition lowered, engagement improved. Recruiters look for the HR functions you own (talent acquisition, HRBP, payroll, L&D) and the HRMS tools you use.',
 'intro2':'The example below turns HR responsibilities into measurable outcomes. Let AI rewrite your duties into the same crisp, ATS-friendly bullets.',
 'person':{
   'name':'Sneha Iyer','title':'HR Manager',
   'contact':'sneha.iyer@email.com · +91 98xxxxxx12 · Chennai, India · linkedin.com/in/snehaiyer',
   'summary':'People-focused HR Manager with 7 years across talent acquisition, HR operations and employee engagement in IT services. Closed 300+ hires, cut time-to-fill by 40% and reduced first-year attrition from 24% to 15% through structured onboarding.',
   'jobs':[
     {'title':'HR Manager','co':'Cognizant','date':'2020 – Present','bullets':[
       'Led a 4-person TA team hiring 300+ engineers/year, cutting time-to-fill from 45 to 27 days',
       'Redesigned onboarding, reducing first-year attrition from 24% to 15%',
       'Rolled out an engagement programme that lifted eNPS by 18 points']},
     {'title':'HR Executive','co':'TCS','date':'2017 – 2020','bullets':[
       'Managed end-to-end payroll for 800+ employees with 100% accuracy on Darwinbox',
       'Coordinated performance appraisals and L&D calendars for 3 business units']},
   ],
   'skills':['Talent Acquisition','HRBP','Payroll','HRMS (Darwinbox)','Employee Engagement','Onboarding','Performance Management','L&D','Labour Compliance','Excel'],
   'edu':'MBA, Human Resources','eduyear':'2017','eduschool':'XLRI, Jamshedpur','ats':94},
 'include':[
   ('Professional summary','Years, HR functions owned (TA, HRBP, payroll) and one quantified people outcome.'),
   ('HR skills & HRMS','Talent acquisition, payroll, HRBP, Darwinbox/SAP SuccessFactors — the ATS keywords for HR.'),
   ('Quantified experience','Hires closed, time-to-fill, attrition, eNPS, employees managed — always numbers.'),
   ('Compliance & tools','Labour law compliance, payroll tools, HRMS platforms you have used.'),
   ('Education & certifications','MBA-HR or a SHRM/HRCI certification if you have one.'),
 ],
 'skills_intro':'These HR keywords are what recruiters and ATS look for:',
 'topskills':['Talent Acquisition','Payroll','HRBP','Employee Engagement','Onboarding','Performance Management','HRMS','L&D','Labour Compliance','Recruitment'],
 'faq':[
   ('What should an HR resume include?','A summary with your HR functions and one people metric, a skills section (talent acquisition, payroll, HRBP, HRMS), and quantified experience — hires, time-to-fill, attrition, eNPS — plus your MBA-HR or SHRM certification.'),
   ('How do I write an HR resume for a fresher?','Highlight your MBA-HR, internships, and any live recruitment, payroll or engagement project. Add HRMS familiarity (Darwinbox, SAP) and a skills section, and quantify anything you supported.'),
   ('Which HR certifications help?','SHRM-CP, HRCI (aPHR/PHR) and platform certifications (Darwinbox, SAP SuccessFactors) are the most recognised. List them clearly.'),
   ('Is the HR resume builder free?','Yes — free to build and edit, no sign-up. PDF download is ₹9 in India; Word is free.'),
 ],
},
{
 'slug':'mechanical-engineer','title':'Mechanical Engineer','badge':'MECHANICAL ENGINEER','plural':'mechanical engineers',
 'meta':'Free mechanical engineer resume example with a real sample. Build an ATS-friendly mechanical engineering resume with AI — CAD, GD&T, manufacturing. No sign-up.',
 'og':'A real mechanical engineer resume example plus an AI builder — ATS-optimised and free.',
 'h1a':'A Mechanical Engineer Resume','h1b':'That Gets Shortlisted',
 'hero':'See a real mechanical engineer resume example, then build yours with AI in minutes. ATS-optimised for Naukri and core-industry recruiters. No sign-up.',
 'intro1':'A mechanical engineering resume should prove design and manufacturing competence: the CAD tools you use (SolidWorks, AutoCAD, CATIA), the processes you know (GD&T, FEA, lean), and the results you delivered — cost cut, cycle time reduced, defects lowered.',
 'intro2':'The example below shows how to frame design and production work as measurable outcomes. Let AI rewrite your project bullets into the same ATS-friendly format.',
 'person':{
   'name':'Arjun Patel','title':'Mechanical Design Engineer',
   'contact':'arjun.patel@email.com · +91 97xxxxxx73 · Ahmedabad, India · linkedin.com/in/arjunpatel',
   'summary':'Mechanical Design Engineer with 4 years in automotive component design and manufacturing. Proficient in SolidWorks, AutoCAD and GD&T. Redesigned a bracket assembly that cut material cost by 18% and reduced production cycle time by 22%.',
   'jobs':[
     {'title':'Mechanical Design Engineer','co':'Tata Motors','date':'2021 – Present','bullets':[
       'Redesigned a bracket assembly in SolidWorks, cutting material cost by 18% and weight by 12%',
       'Applied GD&T and DFM reviews that reduced production defects by 30%',
       'Ran FEA simulations to validate designs, cutting physical prototype iterations from 5 to 2']},
     {'title':'Graduate Engineer Trainee','co':'Bosch','date':'2020 – 2021','bullets':[
       'Created 150+ 2D/3D drawings in AutoCAD and SolidWorks for production tooling',
       'Supported a lean line-balancing project that improved cycle time by 15%']},
   ],
   'skills':['SolidWorks','AutoCAD','CATIA','GD&T','FEA (ANSYS)','DFM/DFA','Lean Manufacturing','Product Design','Root Cause Analysis','MS Project'],
   'edu':'B.E., Mechanical Engineering','eduyear':'2020','eduschool':'COEP, Pune · 8.1 CGPA','ats':93},
 'include':[
   ('Professional summary','Years, domain (automotive, HVAC, manufacturing), key CAD tools and one quantified result.'),
   ('CAD & technical skills','SolidWorks, AutoCAD, CATIA, GD&T, FEA — the exact keywords core-industry ATS screens for.'),
   ('Quantified projects','Cost cut, weight reduced, cycle time improved, defects lowered — numbers in every bullet.'),
   ('Certifications','CSWA/CSWP (SolidWorks), Six Sigma, or an AutoCAD certification.'),
   ('Education','B.E./B.Tech Mechanical with college, year and CGPA.'),
 ],
 'skills_intro':'These are the mechanical-engineering keywords recruiters and ATS filter on:',
 'topskills':['SolidWorks','AutoCAD','CATIA','GD&T','FEA','ANSYS','DFM','Lean Manufacturing','Six Sigma','Product Design'],
 'faq':[
   ('What should a mechanical engineer resume include?','A summary with your domain and CAD tools, a technical skills section (SolidWorks, AutoCAD, GD&T, FEA), quantified project outcomes (cost, weight, cycle time, defects), and your B.E./B.Tech with CGPA plus any CSWA/Six Sigma certification.'),
   ('How do I write a mechanical engineer resume for a fresher?','Lead with academic and internship projects: state the CAD tools used, what you designed or analysed, and the result. Add a strong skills section and CGPA, and any SolidWorks (CSWA) or NPTEL certifications.'),
   ('Which software should I list?','SolidWorks, AutoCAD and CATIA for design; ANSYS for FEA; plus GD&T and any PLM/CAM tools you know. Only list what you can actually use in an interview.'),
   ('Is the mechanical engineer resume builder free?','Yes — build and edit free, no sign-up. PDF download is ₹9 in India; Word is free.'),
 ],
},
{
 'slug':'graphic-designer','title':'Graphic Designer','badge':'GRAPHIC DESIGNER','plural':'designers',
 'meta':'Free graphic designer resume example with a real sample. Build an ATS-friendly graphic design resume with AI — Adobe, Figma, branding, portfolio. No sign-up.',
 'og':'A real graphic designer resume example plus an AI builder — ATS-optimised and free.',
 'h1a':'A Graphic Designer Resume','h1b':'That Stands Out',
 'hero':'See a real graphic designer resume example, then build yours with AI in minutes. ATS-friendly, with a spot for your portfolio link. No sign-up.',
 'intro1':'A graphic designer resume has a double job: pass ATS with the right tool keywords (Photoshop, Illustrator, Figma) and lead the recruiter to your portfolio. It should show range — branding, social, print, UI — and impact, like engagement lifts or faster turnaround.',
 'intro2':'The example below keeps it clean and ATS-safe while showcasing measurable design outcomes. Let AI rewrite your bullets and remember to add your portfolio link at the top.',
 'person':{
   'name':'Meera Desai','title':'Graphic Designer',
   'contact':'meera.desai@email.com · +91 98xxxxxx46 · Mumbai, India · behance.net/meeradesai · linkedin.com/in/meeradesai',
   'summary':'Multidisciplinary Graphic Designer with 5 years across branding, social and packaging for consumer brands. Fluent in the Adobe Creative Suite and Figma. Redesigned a brand identity that grew social engagement by 45% and cut design turnaround by 30%.',
   'jobs':[
     {'title':'Graphic Designer','co':'Ogilvy India','date':'2021 – Present','bullets':[
       'Led a brand-identity redesign for a D2C client that lifted Instagram engagement by 45%',
       'Produced 400+ social and campaign assets/year, cutting average turnaround from 3 days to 2',
       'Built a reusable design system in Figma that reduced repetitive work by 30%']},
     {'title':'Junior Designer','co':'Dentsu','date':'2019 – 2021','bullets':[
       'Designed packaging and print collateral for 15+ FMCG SKUs',
       'Created motion graphics that improved ad completion rate by 20%']},
   ],
   'skills':['Adobe Photoshop','Adobe Illustrator','Adobe InDesign','Figma','Branding','Typography','Social Media Design','Packaging','Motion Graphics','UI Design'],
   'edu':'B.Des, Communication Design','eduyear':'2019','eduschool':'MIT Institute of Design, Pune','ats':90},
 'include':[
   ('Portfolio link','Put a Behance/Dribbble/personal-site link at the top — it is the single most important element.'),
   ('Professional summary','Your years, design areas (branding, social, UI) and one measurable result.'),
   ('Software & skills','Photoshop, Illustrator, InDesign, Figma — the exact keywords design ATS screens for.'),
   ('Quantified experience','Engagement lifts, turnaround cut, assets produced, conversion improved — add numbers where design allows.'),
   ('Keep it ATS-safe','Use a clean, single-column template for the ATS copy; save the heavy visual work for your portfolio.'),
 ],
 'skills_intro':'These design keywords are what recruiters and ATS scan for:',
 'topskills':['Adobe Photoshop','Adobe Illustrator','Adobe InDesign','Figma','Branding','Typography','UI Design','Motion Graphics','Packaging','Social Media Design'],
 'faq':[
   ('What should a graphic designer resume include?','A portfolio link at the top, a short summary, a software/skills section (Photoshop, Illustrator, InDesign, Figma), quantified experience where possible, and your design degree. Keep the resume itself clean and ATS-friendly.'),
   ('Do graphic designers need an ATS-friendly resume?','Yes. Many companies screen resumes through ATS first, so use a clean single-column layout with real text (not an image) and the right tool keywords — then let your portfolio show the creativity.'),
   ('How do I make a designer resume with no experience?','Lead with your portfolio and college/freelance projects: state the brief, tools used and outcome. Add a strong software skills section and any client or competition work.'),
   ('Is the graphic designer resume builder free?','Yes — build and edit free, no sign-up. PDF download is ₹9 in India; Word is free.'),
 ],
},
]
